### ISSUE TITLE
Please remove MUNKI_REPO variable from .munki recipes

### ISSUE THREAD

**Issue by workflowsguy** [autopkg/andrewvalentine-recipes#1]
Could you please remove the MUNKI_REPO variable from disk-sensei.munki (and possibly other recipes) as it overwrites the AutoPkg setting.
This makes it unnecessarily difficult to create an override.
Thanks!

**Comment by andrewvalentine** [comment]
Done! Thanks for raising this. No idea why I hardcoded those variables...

Andrew
