### ISSUE TITLE
disk-sensei.munki Recipe Error

### ISSUE THREAD

**Issue by vmgstudio520** [autopkg/andrewvalentine-recipes#13]
When running the disk-sensei.munki recipe in AutoPkgr the following error message is received:
_"Curl failure: The requested URL returned error: 403 Forbidden (exit code 22)"_

**Comment by andrewvalentine** [comment]
Sorry it's taken so long to get around to this!

Turns out it was a very simple fix, and I've updated all the disk-sensei recipes to reflect this. The Munki recipe specific commit is 6bf586f21e22144e9c4661ddca23247f0deaa3a4.
