### ISSUE TITLE
RaTherapee.munki glob error

### ISSUE THREAD

**Issue by jaw4uz** [autopkg/andrewvalentine-recipes#21]
When running a recipe override for the RawTherapee.munki recipe the following error is popping up:

Error in local.munki.RawTherapeeOverRide: Processor: Copier: Error: Error processing path '/Library/AutoPkg/local.munki.RawTherapeeOverRide/RawTherapee/*.app' with glob

From what I can tell it looks like a RawTherapee_OSX_10.9_64_5.5.dmg is placed in the folder and the .app is not being extracted. 

When I extract the app and place it in the /Library/AutoPkg/local.munki.RawTherapeeOverRide/RawTherapee/ folder the recipe runs with out error.

**Comment by andrewvalentine** [comment]
Awaiting merge of https://github.com/autopkg/peshay-recipes/pull/43

**Comment by andrewvalentine** [comment]
https://github.com/autopkg/peshay-recipes/pull/43 now merged.

I've also updated my `.munki` recipe to use `com.github.peshay.download.RawTherapee` rather than my unneccessary `.pkg` recipe.

To make use of the fixed recipes, please run:

```
autopkg repo-update andrewvalentine-recipes
autopkg repo-update peshay-recipes
```
Thanks.
