### ISSUE TITLE
paintbrush autopkg fails

### ISSUE THREAD

**Issue by hugo4711** [autopkg/andrewvalentine-recipes#37]
` admin$ autopkg run -vv paintbrush.munki
Processing paintbrush.munki...
WARNING: paintbrush.munki is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
SparkleUpdateInfoProvider
{'Input': {'appcast_url': u'http://paintbrush.sourceforge.net/updates2x.xml'}}
SparkleUpdateInfoProvider: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
SparkleUpdateInfoProvider: Version retrieved from appcast: 20190914
SparkleUpdateInfoProvider: User-facing version retrieved from appcast: 2.5
SparkleUpdateInfoProvider: Found URL https://rink.hockeyapp.net/api/2/apps/4b24192a3353453dbf2984d2dd77aaf5/app_versions/28?format=zip
{'Output': {'url': 'https://rink.hockeyapp.net/api/2/apps/4b24192a3353453dbf2984d2dd77aaf5/app_versions/28?format=zip',
            'version': '2.5'}}
URLDownloader
{'Input': {'CURL_PATH': '/usr/bin/curl',
           'url': u'https://rink.hockeyapp.net/api/2/apps/4b24192a3353453dbf2984d2dd77aaf5/app_versions/28?format=zip'}}
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
curl failure: Server aborted the SSL handshake (exit code 35)
Failed.
Receipt written to /Users/admin/Library/AutoPkg/Cache/com.github.andrewvalentine.munki.paintbrush/receipts/paintbrush-receipt-20201124-163428.plist

The following recipes failed:
    paintbrush.munki
        Error in com.github.andrewvalentine.munki.paintbrush: Processor: URLDownloader: Error: curl failure: Server aborted the SSL handshake (exit code 35)

Nothing downloaded, packaged or imported.`

**Comment by andrewvalentine** [comment]
Thanks for the notification. Resolved by https://github.com/autopkg/andrewvalentine-recipes/commit/fc605dea355029f073c66bc51944bb3d8f3e0640.
