### ISSUE TITLE
Use a standard copy_from_dmg for FBMacMessenger

### ISSUE THREAD

**Issue by timsutton** [autopkg/andrewvalentine-recipes#5]
At one point I also wrote a Messenger munki recipe and never published it - I'd rather use yours to avoid duplicating them, but for mine, I just wrapped the .app into a DMG and let MunkiImporter create it as a standard copy-from-dmg rather than using the pkg recipe.

One advantage to doing this is that it will automatically set the appropriate `minimum_os_version` by deriving it from the app, and also create an installs key for it.

Would you accept a PR to modify your `FBMacMessenger.munki` to use this logic instead of using the .pkg recipe as a parent?

**Comment by andrewvalentine** [comment]
Sorry for the delay. Happy to accept a PR. I wrote the `.pkg` and `.munki` recipes mostly as a learning exercise, not expecting either to get much usage. Copy-from-dmg is more sensible, so yes, please go for it.
